name: hls

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - design.v
  - run.vcd

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - python3 rtl_vcd_gen.py
  - python3 remove_duplicate_modules.py
  - cp ../../build/1-hls/build/Pathtracer.v1/concat_rtl_trimmed.v  outputs/design.v
  - cp ../../build/1-hls/Pathtracer.vcd outputs/run.vcd

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 9.0
  